NAME='nmt'
USER='ubuntu'

DIR=/opt/$NAME
ENV_PATH=$DIR/env
DATA_PATH=$DIR/data

REQ_BOT_FILE_PATH=req_bot.txt
MODEL_FILE_PATH=$DATA_PATH/model.pt
SRC_TOK_FILE_PATH=$DATA_PATH/ru_bpe.yttm
TRG_TOK_FILE_PATH=$DATA_PATH/en_bpe.yttm

SERVICE_NAME="${NAME}_bot.service"
SERVICE_FILE_TEMPLATE_PATH=bot.service
SERVICE_FILE_PATH=/etc/systemd/system/$SERVICE_NAME

MODEL_FILE_ID=1heNu80X8DcTKTx2Od0-EW-6JrkXxk5Ze
SRC_TOK_FILE_ID=1c4LakbKi7-gbKyAvcoGkJ8Yic16wvJx0
TRG_TOK_FILE_ID=1I46t9Qgz0NbXjT-EPbogEUYpvGPTc408
TG_BOT_API_FILE_ID=1joBeJBXpwY1yrvWt6DzjX_aLy89RPNF7